### ISSUE TITLE
tractome with Python3

### ISSUE THREAD

**Issue by neurolabusc** [FBK-NILab/tractome#25]
Tractome works nicely on my MacOS computer. However, I have not been able to get it to install on my Ubuntu 20.04 machine. Is there documentation that can help?
1. Ubuntu 20.04 no longer comes with Python2 by default, and when I tried to run Tractome it seems incompatible with Python 3, e.g. invalid syntax for line 267 in mainwindow.py
 except TractomeError, e:
2. I did install an old Python 2.7, but adding required modules like PySide seems to be challenging. If Tractome can not be upgraded to support Python3, perhaps the documentation could be updated to describe installation on a modern Linux OS.

Thanks for developing this lovely tool.

**Comment by pietroastolfi** [comment]
Hi @neurolabusc,
I apologize for the lack of compatibility with python 3, but it will be a future upgrade. Nevertheless, I updated the instructions on how to run Tractome using conda under recent Ubuntu (tried on 18.04 and 20.04). Let me know if the instructions are not clear or if you continue to have problems.

**Comment by neurolabusc** [comment]
Great. In addition to Github, you may want to update the instructions at [http://tractome.org/](http://tractome.org/).
